"""agregar validacion de estado producto en cambios

Revision ID: 3e1674bc0a91
Revises: 7645ca7d4256
Create Date: 2026-08-23 19:17:12.031084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1674bc0a91'
down_revision: Union[str, Sequence[str], None] = '7645ca7d4256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cambios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('venta_original_id', sa.String(length=36), nullable=False),
    sa.Column('fecha_cambio', sa.DateTime(), nullable=False),
    sa.Column('cajero_id', sa.String(length=36), nullable=False),
    sa.Column('producto_a_cambiar_id', sa.String(length=36), nullable=False),
    sa.Column('nuevo_producto_id', sa.String(length=36), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.Column('fecha_compra_original', sa.DateTime(), nullable=True),
    sa.Column('estado_producto', sa.String(length=20), nullable=True),
    sa.Column('tiene_etiqueta', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('fecha_validacion', sa.DateTime(), nullable=True),
    sa.CheckConstraint("estado_producto IN ('NUEVO_ETIQUETADO', 'USADO', 'DANADO')", name='ck_cambios_estado_producto'),
    sa.ForeignKeyConstraint(['venta_original_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cambios')
    # ### end Alembic commands ###
